name: selo

services:
  postgres:
    image: postgres
    container_name: selo-postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
      - POSTGRES_DB=selo
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d selo"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data

  # redis:
  #   image: redis
  #   container_name: redis.selo
  #   ports:
  #     - "6379:6379"
      
  app:
    container_name: selo-app
    platform: linux/amd64
    volumes:
      - "$ROOT:/app:delegated"
    build:
      context: "$ROOT"
      dockerfile_inline: |
        FROM node:20-alpine
        VOLUME /app
        WORKDIR /app
        RUN npm install -g @nestjs/cli
        USER node
        CMD npm run start:dev
    environment:
      - PORT=8080
      - DATABASE_URL=postgres://root:toor@selo-postgres:5432/selo
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres: